from sqlalchemy.orm import Session
from models import Game, UserPreference

SEED_GAMES = [
    {
        "title": "Cyberstrike Horizon 2088",
        "description": "Fast-paced futuristic multiplayer FPS set in a neon-drenched metropolis. Features high-mobility jetpacks, custom energy weaponry, and 64-player tactical objective combat.",
        "genre": "Shooter",
        "subgenre": "Tactical FPS",
        "platform": "PC, PlayStation, Xbox",
        "multiplayer": True,
        "single_player": True,
        "difficulty": "Hard",
        "gameplay_style": "Competitive",
        "theme": "Futuristic",
        "release_year": 2024,
        "rating": 4.8,
        "price": 59.99,
        "image_url": "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=800&q=80",
        "tags": "Futuristic, FPS, Neon, Jetpacks, Competitive, Multiplayer"
    },
    {
        "title": "Starlight Haven: Farmers of Tomorrow",
        "description": "A deeply relaxing sci-fi farming simulator where you grow bioluminescent alien flora, construct automated solar green-domes, and harmonize with gentle local fauna.",
        "genre": "Farming",
        "subgenre": "Life Sim",
        "platform": "PC, Nintendo, Mobile",
        "multiplayer": True,
        "single_player": True,
        "difficulty": "Easy",
        "gameplay_style": "Relaxing & Casual",
        "theme": "Relaxing",
        "release_year": 2023,
        "rating": 4.9,
        "price": 19.99,
        "image_url": "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=80",
        "tags": "Farming, Cozy, Relaxing, Space, Alien Flora, Crafting"
    },
    {
        "title": "Chrono Matrix 2D",
        "description": "Mind-bending 2D perspective puzzle adventure where time moves only when you move. Tackle 120 handcrafted rooms with progressively brutal logic mechanics.",
        "genre": "Puzzle",
        "subgenre": "Logic Platformer",
        "platform": "PC, Nintendo, Mobile, Browser",
        "multiplayer": False,
        "single_player": True,
        "difficulty": "Hard",
        "gameplay_style": "Logic & Problem Solving",
        "theme": "Sci-Fi",
        "release_year": 2023,
        "rating": 4.7,
        "price": 14.99,
        "image_url": "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=800&q=80",
        "tags": "Puzzle, 2D, Time Manipulation, Increasing Difficulty, Indie"
    },
    {
        "title": "Eldoria: Shadows of the Ancient Tree",
        "description": "An open-world action RPG featuring elemental magic combinations, deep skill trees, and colossal mythic titan battles in a breathtaking high-fantasy continent.",
        "genre": "RPG",
        "subgenre": "Action RPG",
        "platform": "PC, PlayStation, Xbox",
        "multiplayer": True,
        "single_player": True,
        "difficulty": "Medium",
        "gameplay_style": "Open-World Exploration",
        "theme": "Fantasy",
        "release_year": 2024,
        "rating": 4.9,
        "price": 69.99,
        "image_url": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80",
        "tags": "Open World, Fantasy, RPG, Magic, Boss Fights, Epic Story"
    },
    {
        "title": "Apex Velocity: Hyper Drift",
        "description": "High-octane arcade racing with anti-gravity vehicles, loop-de-loops, and pulse-pounding synthwave soundtracks across orbital megastructure tracks.",
        "genre": "Racing",
        "subgenre": "Arcade Racing",
        "platform": "PC, PlayStation, Xbox, Nintendo",
        "multiplayer": True,
        "single_player": True,
        "difficulty": "Medium",
        "gameplay_style": "Competitive",
        "theme": "Futuristic",
        "release_year": 2023,
        "rating": 4.6,
        "price": 29.99,
        "image_url": "https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=800&q=80",
        "tags": "Racing, Anti-Gravity, Synthwave, Speed, Multiplayer"
    },
    {
        "title": "Void Sector: Galactic Command",
        "description": "Grand real-time strategy where you manage orbital fleet logistics, terraform planetary colonies, and command thousand-ship space armadas.",
        "genre": "Strategy",
        "subgenre": "RTS / 4X",
        "platform": "PC",
        "multiplayer": True,
        "single_player": True,
        "difficulty": "Hard",
        "gameplay_style": "Logic & Problem Solving",
        "theme": "Sci-Fi",
        "release_year": 2024,
        "rating": 4.8,
        "price": 49.99,
        "image_url": "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80",
        "tags": "RTS, Strategy, Space Armada, Command, Base Building"
    },
    {
        "title": "Phantasm Abyss: Deep Terror",
        "description": "Psychological survival horror set in an underwater research station 10,000 meters beneath frozen ice crusts. Manage oxygen, sanity, and light against sound-sensitive deep sea abominations.",
        "genre": "Horror",
        "subgenre": "Survival Horror",
        "platform": "PC, PlayStation, Xbox",
        "multiplayer": False,
        "single_player": True,
        "difficulty": "Hard",
        "gameplay_style": "Story-Driven",
        "theme": "Dark",
        "release_year": 2023,
        "rating": 4.7,
        "price": 34.99,
        "image_url": "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80",
        "tags": "Horror, Survival, Deep Sea, Dark, Stealth, Atmospheric"
    },
    {
        "title": "Pixel Knight: Realm Defender",
        "description": "Charming retro 2D action platformer with tight wall-jumping controls, hidden secret dungeons, pixel-art bosses, and nostalgic 16-bit chiptune audio.",
        "genre": "Platformer",
        "subgenre": "2D Action Platformer",
        "platform": "PC, Nintendo, Mobile, Browser",
        "multiplayer": False,
        "single_player": True,
        "difficulty": "Medium",
        "gameplay_style": "Action-Packed",
        "theme": "Retro",
        "release_year": 2022,
        "rating": 4.6,
        "price": 9.99,
        "image_url": "https://images.unsplash.com/photo-1551103782-8ab07afd45c1?auto=format&fit=crop&w=800&q=80",
        "tags": "Platformer, 2D, Pixel Art, Retro, Indie, Bosses"
    },
    {
        "title": "Quantum Odyssey: Infinite Sandbox",
        "description": "Unlimited voxel sandbox adventure where players manipulate atomic matter, build automated quantum circuits, and travel between infinite procedurally generated dimensions.",
        "genre": "Simulation",
        "subgenre": "Voxel Sandbox",
        "platform": "PC, PlayStation, Xbox, Mobile",
        "multiplayer": True,
        "single_player": True,
        "difficulty": "Easy",
        "gameplay_style": "Open-World Exploration",
        "theme": "Sci-Fi",
        "release_year": 2023,
        "rating": 4.9,
        "price": 0.0,
        "image_url": "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=800&q=80",
        "tags": "Sandbox, Crafting, Similar to Minecraft, Voxel, Multiplayer, Free to Play"
    },
    {
        "title": "Neon Siege: Cyber Vanguard",
        "description": "Tactical squad-based multiplayer hero shooter featuring futuristic gadgets, destructible neon city arenas, and high-stakes ranked seasonal leagues.",
        "genre": "Shooter",
        "subgenre": "Hero Shooter",
        "platform": "PC, PlayStation, Xbox",
        "multiplayer": True,
        "single_player": False,
        "difficulty": "Hard",
        "gameplay_style": "Competitive",
        "theme": "Futuristic",
        "release_year": 2024,
        "rating": 4.7,
        "price": 0.0,
        "image_url": "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&w=800&q=80",
        "tags": "Shooter, Futuristic, Hero Shooter, Ranked, Cyberpunk, Free to Play"
    },
    {
        "title": "Meadowlands Cozy Life",
        "description": "Wholesome life simulation game centered on baking artisanal pastries, decorating rural cottages, and fostering heartwarming friendships with forest villagers.",
        "genre": "Simulation",
        "subgenre": "Cozy Life Sim",
        "platform": "Nintendo, Mobile, PC",
        "multiplayer": True,
        "single_player": True,
        "difficulty": "Easy",
        "gameplay_style": "Relaxing & Casual",
        "theme": "Relaxing",
        "release_year": 2023,
        "rating": 4.8,
        "price": 14.99,
        "image_url": "https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?auto=format&fit=crop&w=800&q=80",
        "tags": "Relaxing, Cozy, Baking, Decoration, Cute, Cottagecore"
    },
    {
        "title": "Aetheria: Legend of the Sky Islands",
        "description": "Soar across floating celestial islands aboard custom airships, solving elemental puzzles and uncovering the ancient lore of a lost airborne civilization.",
        "genre": "Adventure",
        "subgenre": "Story Adventure",
        "platform": "PC, PlayStation, Nintendo",
        "multiplayer": False,
        "single_player": True,
        "difficulty": "Medium",
        "gameplay_style": "Story-Driven",
        "theme": "Fantasy",
        "release_year": 2023,
        "rating": 4.9,
        "price": 39.99,
        "image_url": "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80",
        "tags": "Adventure, Airships, Sky Islands, Lore, Story-Rich, Puzzle"
    },
    {
        "title": "Overclocked: Synthwave Brawl",
        "description": "Brutal 1v1 and 4-player couch fighting game with customizable cyborg cyberware, parry mechanics, and aggressive combat set in retro 80s neon arenas.",
        "genre": "Action",
        "subgenre": "Fighting / Brawler",
        "platform": "PC, PlayStation, Xbox",
        "multiplayer": True,
        "single_player": True,
        "difficulty": "Hard",
        "gameplay_style": "Competitive",
        "theme": "Futuristic",
        "release_year": 2023,
        "rating": 4.5,
        "price": 24.99,
        "image_url": "https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=800&q=80",
        "tags": "Action, Fighting, Cyborgs, Synthwave, Brawler, Competitive"
    },
    {
        "title": "Zen Garden Tactics",
        "description": "Serene turn-based tactical puzzle game where players arrange stones, direct water streams, and cultivate glowing lotus flowers to restore harmony.",
        "genre": "Puzzle",
        "subgenre": "Turn-based Puzzle",
        "platform": "PC, Mobile, Browser",
        "multiplayer": False,
        "single_player": True,
        "difficulty": "Easy",
        "gameplay_style": "Logic & Problem Solving",
        "theme": "Relaxing",
        "release_year": 2022,
        "rating": 4.7,
        "price": 4.99,
        "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
        "tags": "Puzzle, Zen, Chill, Relaxing, Minimalist, Logic"
    },
    {
        "title": "Starship Vanguard 2099",
        "description": "Single-player story campaign FPS where players infiltrate enemy dreadnoughts with railguns, plasma blades, and gravity-bending abilities.",
        "genre": "Shooter",
        "subgenre": "Sci-Fi Campaign FPS",
        "platform": "PC, PlayStation, Xbox",
        "multiplayer": False,
        "single_player": True,
        "difficulty": "Medium",
        "gameplay_style": "Action-Packed",
        "theme": "Futuristic",
        "release_year": 2024,
        "rating": 4.8,
        "price": 49.99,
        "image_url": "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80",
        "tags": "Shooter, Futuristic Weapons, Sci-Fi, Story Campaign, Railgun"
    },
    {
        "title": "Supercharge Rally cross",
        "description": "Mud-splattered realistic rally racing simulation with dynamic weather effects, realistic suspension physics, and global leaderboard time trials.",
        "genre": "Racing",
        "subgenre": "Sim Racing",
        "platform": "PC, PlayStation, Xbox",
        "multiplayer": True,
        "single_player": True,
        "difficulty": "Hard",
        "gameplay_style": "Competitive",
        "theme": "Modern",
        "release_year": 2023,
        "rating": 4.6,
        "price": 49.99,
        "image_url": "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80",
        "tags": "Racing, Rally, Simulation, Off-Road, Leaderboards"
    },
    {
        "title": "Mythic Dungeon Crawl",
        "description": "Fast-paced isometric hack-and-slash ARPG with endless procedurally generated dungeons, thousands of legendary loot drops, and class build freedom.",
        "genre": "RPG",
        "subgenre": "Action RPG / Dungeon Crawler",
        "platform": "PC, PlayStation, Xbox, Nintendo",
        "multiplayer": True,
        "single_player": True,
        "difficulty": "Medium",
        "gameplay_style": "Action-Packed",
        "theme": "Dark",
        "release_year": 2023,
        "rating": 4.7,
        "price": 29.99,
        "image_url": "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=800&q=80",
        "tags": "RPG, Dungeon Crawler, Loot, Hack and Slash, Dark Fantasy"
    },
    {
        "title": "Neon Gridiron Football 2025",
        "description": "Futuristic cyberpunk sports game where cybernetically enhanced athletes play high-velocity contact football with energy shields and gravity balls.",
        "genre": "Sports",
        "subgenre": "Futuristic Sports",
        "platform": "PC, PlayStation, Xbox",
        "multiplayer": True,
        "single_player": True,
        "difficulty": "Medium",
        "gameplay_style": "Competitive",
        "theme": "Futuristic",
        "release_year": 2024,
        "rating": 4.4,
        "price": 39.99,
        "image_url": "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=800&q=80",
        "tags": "Sports, Cyberpunk, Futuristic, Football, Multiplayer"
    },
    {
        "title": "Astral Farmer: Galaxy Crop",
        "description": "Charming interstellar space farming game where you navigate asteroid belts, build automatic greenhouse pods, and sell cosmic fruits to interstellar traders.",
        "genre": "Farming",
        "subgenre": "Sci-Fi Sim",
        "platform": "PC, Nintendo, Mobile",
        "multiplayer": True,
        "single_player": True,
        "difficulty": "Easy",
        "gameplay_style": "Relaxing & Casual",
        "theme": "Relaxing",
        "release_year": 2023,
        "rating": 4.8,
        "price": 14.99,
        "image_url": "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=800&q=80",
        "tags": "Farming, Space, Galaxy, Relaxing, Casual, Trade"
    },
    {
        "title": "Ghost Ops: Covert Strike",
        "description": "Tactical stealth third-person shooter focusing on infiltration, optical camouflage gadgets, sync shots, and realistic ballistic mechanics.",
        "genre": "Shooter",
        "subgenre": "Stealth Shooter",
        "platform": "PC, PlayStation, Xbox",
        "multiplayer": True,
        "single_player": True,
        "difficulty": "Hard",
        "gameplay_style": "Competitive",
        "theme": "Modern",
        "release_year": 2023,
        "rating": 4.6,
        "price": 59.99,
        "image_url": "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=800&q=80",
        "tags": "Shooter, Stealth, Tactical, Modern, Co-op"
    },
    {
        "title": "Spellbound Tower: 100 Floors",
        "description": "Roguelike deck-building puzzle game where players combine magical runes to climb a hundred floors of magical challenges with random encounters.",
        "genre": "Puzzle",
        "subgenre": "Deckbuilder Puzzle",
        "platform": "PC, Mobile, Nintendo",
        "multiplayer": False,
        "single_player": True,
        "difficulty": "Hard",
        "gameplay_style": "Logic & Problem Solving",
        "theme": "Fantasy",
        "release_year": 2023,
        "rating": 4.9,
        "price": 12.99,
        "image_url": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80",
        "tags": "Puzzle, Deckbuilder, Roguelike, Magic, Hard"
    },
    {
        "title": "Cyber City Detective: 2099",
        "description": "Immersive narrative story-driven adventure game. Investigate corporate corruption, hack neural terminals, and make game-changing dialogue choices.",
        "genre": "Adventure",
        "subgenre": "Cyberpunk Narrative",
        "platform": "PC, PlayStation, Xbox",
        "multiplayer": False,
        "single_player": True,
        "difficulty": "Easy",
        "gameplay_style": "Story-Driven",
        "theme": "Futuristic",
        "release_year": 2024,
        "rating": 4.7,
        "price": 29.99,
        "image_url": "https://images.unsplash.com/photo-1514565131-fce0801e5785?auto=format&fit=crop&w=800&q=80",
        "tags": "Adventure, Cyberpunk, Story-Driven, Futuristic, Hacking"
    },
    {
        "title": "Super Block Crafters",
        "description": "Relaxing block-building open-world sandbox game with endless exploration, redstone-style electronic circuits, and custom multiplayer server support.",
        "genre": "Simulation",
        "subgenre": "Sandbox",
        "platform": "PC, PlayStation, Xbox, Nintendo, Mobile, Browser",
        "multiplayer": True,
        "single_player": True,
        "difficulty": "Easy",
        "gameplay_style": "Open-World Exploration",
        "theme": "Retro",
        "release_year": 2022,
        "rating": 4.9,
        "price": 26.95,
        "image_url": "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=800&q=80",
        "tags": "Minecraft Similar, Sandbox, Blocks, Crafting, Multiplayer, Open World"
    },
    {
        "title": "Silent Echoes: Abandoned Asylum",
        "description": "Terrifying first-person horror exploration game where your camera flashlight is your only defense against shape-shifting spectral entities.",
        "genre": "Horror",
        "subgenre": "Atmospheric Horror",
        "platform": "PC, PlayStation",
        "multiplayer": False,
        "single_player": True,
        "difficulty": "Hard",
        "gameplay_style": "Story-Driven",
        "theme": "Dark",
        "release_year": 2023,
        "rating": 4.5,
        "price": 19.99,
        "image_url": "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80",
        "tags": "Horror, Scary, Asylum, Ghosts, First Person, Dark"
    },
    {
        "title": "Apex Tennis Pro 2025",
        "description": "Realistic tennis simulation with real-time motion capture animations, career grand-slam modes, and online ranking tournaments.",
        "genre": "Sports",
        "subgenre": "Tennis Sim",
        "platform": "PC, PlayStation, Xbox, Nintendo",
        "multiplayer": True,
        "single_player": True,
        "difficulty": "Medium",
        "gameplay_style": "Competitive",
        "theme": "Modern",
        "release_year": 2024,
        "rating": 4.3,
        "price": 39.99,
        "image_url": "https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?auto=format&fit=crop&w=800&q=80",
        "tags": "Sports, Tennis, Simulation, Tournament, Competitive"
    },
    {
        "title": "Galaxy Battlefront: Starfighter",
        "description": "Epic 32-v-32 online multiplayer starfighter dogfighting shooter set in deep outer space with customizable laser cannons and shield generators.",
        "genre": "Shooter",
        "subgenre": "Space Dogfight FPS",
        "platform": "PC, PlayStation, Xbox",
        "multiplayer": True,
        "single_player": True,
        "difficulty": "Medium",
        "gameplay_style": "Competitive",
        "theme": "Futuristic",
        "release_year": 2024,
        "rating": 4.8,
        "price": 49.99,
        "image_url": "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=800&q=80",
        "tags": "Shooter, Space, Futuristic Weapons, Dogfight, Multiplayer"
    },
    {
        "title": "Cozy Island Rancher",
        "description": "Unwind on a sun-drenched tropical island where you rescue cute exotic creatures, harvest tropical fruit trees, and construct seaside beach houses.",
        "genre": "Farming",
        "subgenre": "Casual Sim",
        "platform": "PC, Nintendo, Mobile, Browser",
        "multiplayer": True,
        "single_player": True,
        "difficulty": "Easy",
        "gameplay_style": "Relaxing & Casual",
        "theme": "Relaxing",
        "release_year": 2023,
        "rating": 4.9,
        "price": 14.99,
        "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
        "tags": "Farming, Island, Cozy, Relaxing, Cute, Creatures"
    },
    {
        "title": "Hyper Laser 2D Breaker",
        "description": "High-speed neon arcade puzzle game where you shoot energy balls to clear cascading brick matrices with explosive chain reactions.",
        "genre": "Puzzle",
        "subgenre": "Arcade Puzzle",
        "platform": "PC, Mobile, Browser",
        "multiplayer": False,
        "single_player": True,
        "difficulty": "Medium",
        "gameplay_style": "Action-Packed",
        "theme": "Retro",
        "release_year": 2022,
        "rating": 4.5,
        "price": 2.99,
        "image_url": "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=800&q=80",
        "tags": "Puzzle, Arcade, 2D, Neon, Increasing Difficulty"
    },
    {
        "title": "Kingdom Strategy: Siege Command",
        "description": "Medieval strategy game centered on building formidable castle fortresses, recruiting knight legions, and defending against enemy siege weapons.",
        "genre": "Strategy",
        "subgenre": "Medieval RTS",
        "platform": "PC",
        "multiplayer": True,
        "single_player": True,
        "difficulty": "Hard",
        "gameplay_style": "Logic & Problem Solving",
        "theme": "Fantasy",
        "release_year": 2023,
        "rating": 4.7,
        "price": 34.99,
        "image_url": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80",
        "tags": "Strategy, Medieval, Siege, Knights, Castle Building"
    },
    {
        "title": "Nebula Survivor 2D",
        "description": "Addictive top-down 2D sci-fi arena shooter where you pilot a combat drone against tens of thousands of alien insect waves with auto-firing laser turrets.",
        "genre": "Indie",
        "subgenre": "Arena Shooter / Bullet Hell",
        "platform": "PC, Mobile, Browser",
        "multiplayer": False,
        "single_player": True,
        "difficulty": "Medium",
        "gameplay_style": "Action-Packed",
        "theme": "Sci-Fi",
        "release_year": 2023,
        "rating": 4.8,
        "price": 4.99,
        "image_url": "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&w=800&q=80",
        "tags": "Indie, 2D, Arena Shooter, Bullet Hell, Upgrades, Space"
    }
]

def seed_database(db: Session):
    # Check if games already exist
    existing_count = db.query(Game).count()
    if existing_count >= 30:
        print(f"[SeedData] Database already seeded with {existing_count} games.")
        return

    print("[SeedData] Seeding database with 30 sample games...")
    for game_dict in SEED_GAMES:
        game = Game(**game_dict)
        db.add(game)

    # Add default user preference
    pref = db.query(UserPreference).filter(UserPreference.user_id == "default_user").first()
    if not pref:
        default_pref = UserPreference(
            user_id="default_user",
            favorite_genres="Shooter, RPG, Action, Farming, Puzzle",
            favorite_platforms="PC, PlayStation, Xbox",
            difficulty="Medium",
            game_mode="Both"
        )
        db.add(default_pref)

    db.commit()
    print(f"[SeedData] Seeding completed. Total games in DB: {db.query(Game).count()}")
